### PR TITLE
update to new pkce oauth flow (ornicar/lila#9214)

### PR DESCRIPTION
**Pull request by niklasf**
for ornicar/lila#9214, following https://github.com/lakinwecker/lichess-oauth-flask/pull/6

### CODE REVIEW

**Comment by michael1241** [comment]
It doesn't need the discord bot token anymore?

**Comment by niklasf** [comment]
That's just a drive-by change unrelated to PKCE. Sorry. Below
```
headers = {'Authorization': f'Bot {os.getenv("DISCORD_TOKEN")}'}
```
uses getenv directly again.

**Comment by michael1241** [comment]
Ah in that case my bad! Would it make more sense to keep the assignment at the top and just use that later on instead of looking it up later? (more of a general question, I can make the change if you agree just wondering what's "correct").

**Comment by niklasf** [comment]
Probably yes, yeah.

**Comment by michael1241** [comment]
I tried to do it and messed up my local repo... will just merge yours :)

**Pull request merged**
